USE springblog_db;
insert into posts (title, body) values ('Profound', 'lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non');
insert into posts (title, body) values ('Open-architected', 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum');
insert into posts (title, body) values ('Re-contextualized', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient');
insert into posts (title, body) values ('capacity', 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel');
insert into posts (title, body) values ('infrastructure', 'justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus');
insert into posts (title, body) values ('Cross-platform', 'cum sociis natoque penatibus et magnis dis parturient montes nascetur');
insert into posts (title, body) values ('foreground', 'enim sit amet nunc viverra dapibus nulla suscipit ligula in');
insert into posts (title, body) values ('zero tolerance', 'morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet');
insert into posts (title, body) values ('needs-based', 'viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et');
insert into posts (title, body) values ('Polarised', 'arcu sed augue aliquam erat volutpat in congue etiam justo etiam');